fix underline at bottom of navbar #2
pandevs-org/rumblesheetJS-website pull request #4
Opened 2024-12-11 07:40 UTC by OMIIIEE

![image](https://github.com/user-attachments/assets/6e9429fe-150d-4560-af5b-c7454c9d8d28)
fixed and made underline at the bottom of the navbar and also fixed underline behavior in responsive page 
![image](https://github.com/user-attachments/assets/4fe4ddf2-5500-4b00-a626-62bc8ad51abd)

2024-12-11 16:07 UTC, BorisEdison commented
> ![image](https://private-user-images.githubusercontent.com/117626285/394624758-6e9429fe-150d-4560-af5b-c7454c9d8d28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzMyMjksIm5iZiI6MTczMzkzMjkyOSwicGF0aCI6Ii8xMTc2MjYyODUvMzk0NjI0NzU4LTZlOTQyOWZlLTE1MGQtNDU2MC1hZjViLWM3NDU0YzlkOGQyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNjAyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZmE2YWFkYWY0MmEwZWE2NDYwNDU3NzRhZTlmNGVmMjI1YzFkNmFlOTkzMzEyODdlYzZhODUxNTFkMzM1N2RjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.15Gay--LCd63V6Lsf-Dhfl0QyCl8fBFsyrEASXCa-l0) fixed and made underline at the bottom of the navbar and also fixed underline behavior in responsive page ![image](https://private-user-images.githubusercontent.com/117626285/394625246-4fe4ddf2-5500-4b00-a626-62bc8ad51abd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzM5MzMyMjksIm5iZiI6MTczMzkzMjkyOSwicGF0aCI6Ii8xMTc2MjYyODUvMzk0NjI1MjQ2LTRmZTRkZGYyLTU1MDAtNGIwMC1hNjI2LTYyYmM4YWQ1MWFiZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxMVQxNjAyMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iZjgwMThiZjg3Mjc4NzM4NzEzYzM2M2JiNTAyOWVlYzE4Njc2Yjg0ZjMyNjQwZmI1MTVhMTA0M2U5NTc3NTJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4zwQdWIEUBP5e3yUAoveeC5uhRK7OiOdgMqYex3m0R0)

![image](https://github.com/user-attachments/assets/7bdfb0f0-14d2-4a38-8c9d-ae6e77fdcee3)
#### its looking like this, 

![image](https://github.com/user-attachments/assets/3d415eff-aada-471f-ab35-0ac78c56d2d5)
#### 20px suits better, check and let me know

#### and please shift the js to this file

https://github.com/pandevs-org/rumblesheetJS-website/blob/main/public/js/index.js

2024-12-11 16:19 UTC, BorisEdison commented on public/styles/navbar.css
> +	bottom: -24px;
20px suits better it seems, but make sure to keep the navbar height to at max 75px 
![image](https://github.com/user-attachments/assets/5de81689-fb31-406f-8bc4-7246b6d59f96)

2024-12-11 16:19 UTC, BorisEdison commented on index.html
> +<script>
shift this code to js file 
https://github.com/pandevs-org/rumblesheetJS-website/blob/main/public/js/index.js

2024-12-11 16:19 UTC, BorisEdison commented on views/docs/latest/getting-started/getting-started.html
> +    <script>
shift this code to js file
https://github.com/pandevs-org/rumblesheetJS-website/blob/main/public/js/index.js

2024-12-11 16:57 UTC, OMIIIEE commented
yes sure ! I'll Make the changes @BorisEdison

2024-12-11 17:03 UTC, OMIIIEE commented
please review the changes and let me know to change anything . after setting max height to 75px it looks like this , but I have to set margin to 18px as for 20px it goes out of navbar in my browser 
![image](https://github.com/user-attachments/assets/cb0c116e-9f81-4ae6-b14c-77dfc8fef1ed)
 
![image](https://github.com/user-attachments/assets/e20641c1-2fb7-4871-9eab-b29006810969)

2024-12-12 06:35 UTC, BorisEdison requested changes

2024-12-12 06:35 UTC, BorisEdison commented on index.html
> +<script>
remove this code here, as it is already present in index.js

2024-12-12 06:35 UTC, BorisEdison commented on public/styles/navbar.css
> -	padding: 24px 48px 8px;
for navbar-unscrolled its not required that the navbar is restricted to 75px max and it also need to be vertically centered,

you can check the behaviour I want in https://borisedison.in for reference

2024-12-13 15:51 UTC, BorisEdison approved these changes

2024-12-13 15:51 UTC, merged